apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-listen-app-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-listen-app-chart.name" . }}
    helm.sh/chart: {{ include "my-listen-app-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-listen-app-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my-listen-app-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: my-listen-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: AUTHOR
              value: "{{ .Values.author }}"
          readinessProbe:
            httpGet:
              path: /author
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /id
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20