apiVersion: v1
kind: Service
metadata:
  name: my-listen-app-service
  namespace: your-namespace
spec:
  selector:
    app: my-listen-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000